---
- name: Creacion de usuarios
  hosts: todos
  vars_files:
    - vars/usuarios.yml
  become: yes
  tasks:
    - name: Creando usuarios para servidores basados en Debian
      user:
        name: "{{ item.nombre }}"
        comment: "{{ item.comentario }}"
        groups: "{{ item.gruposDebian }}"
        append: yes
        shell: "{{ item.shell }}"
        password: "{{ item.clave }}"
      with_items: 
        "{{usuarios}}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - name: Creando usuarios para servidores basados en Red Hat
      user:
        name: "{{ item.nombre }}"
        comment: "{{ item.comentario }}"
        groups: "{{ item.gruposRedHat }}"
        append: yes
        shell: "{{ item.shell }}"
        password: "{{ item.clave }}"
      with_items: 
        "{{usuarios}}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Copiando llaves de SSH
      authorized_key:
        user: "{{ item.nombre }}"
        state: present
        key: "{{ lookup('file', 'ssh_keys/{{ item.llave }}') }}"
      with_items: 
        "{{usuarios}}"
